# This is a basic workflow to help you get started with Actions

name: Docker image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
jobs:
  push_to_registries:
      name: Push Docker image to multiple registries
      runs-on: ubuntu-latest

      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build and publish Docker image
        uses: kavithasivakavi/github_actions@1.0
        with:
         image: kavithasivakavi/github_actions_cicd
         registry: docker.io
         dockerfile: Dockerfile
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}

     
    
